const INITIAL_PAGE = 'INITIAL_PAGE';
const SIGN_IN = 'SIGN_IN';
const VERIFY_PHONE = 'VERIFY_PHONE';
const WELCOME_PAGE = 'WELCOME_PAGE';

export {
  INITIAL_PAGE,
  SIGN_IN,
  VERIFY_PHONE,
  WELCOME_PAGE,
};
